CREATE TABLE profile 
(`sno` INT(22) NOT NULL AUTO_INCREMENT ,
 `fName` VARCHAR(55) NOT NULL , 
 `email` VARCHAR(55) NOT NULL , 
 `bio` VARCHAR(255) NOT NULL ,
 PRIMARY KEY (`sno`)) ENGINE = InnoDB;